events {
    # Define o número de conexões simultâneas que o nginx pode aceitar.
    # 1024 é um valor padrão razoável.
    worker_connections 1024;
}

http {

    # Define um bloco de servidor HTTP.
    # Dentro dele ficam as regras de como o nginx vai responder às requisições.
    server {

        # Diz em qual porta o nginx vai escutar.
        # 80 é a porta padrão para HTTP.
        listen 80;

        # Define quais domínios/nomes de host ativam este bloco.
        # O "_" é um valor convencional usado como "catch-all":
        # qualquer domínio que chegar aqui será aceito.
        server_name _;

        # Define uma regra para URLs que começam com "/".
        # Como "/" engloba todas as rotas, tudo passa por esta regra.
        location / {

            # Encaminha a requisição para outro serviço.
            # Aqui "site" não é um domínio.
            # É o nome do serviço definido no docker-compose:
            # services:
            #   site:
            # O Docker Compose cria uma rede interna e resolve:
            # nginx-proxy --> site:80
            proxy_pass http://site:80;

            # Mantém o domínio original enviado pelo cliente.
            # Exemplo:
            # Usuário acessa:
            # https://site.com
            # Sem isso, o container receberia:
            # Host: site
            # Com isso:
            # Host: site.com
            proxy_set_header Host $host;

            # Envia para o container o IP real do cliente.
            proxy_set_header X-Real-IP $remote_addr;

            # Mantém a cadeia completa de IPs.
            # Exemplo: Cliente -> Cloudflare -> Nginx -> Container
            # Esse header guarda essa sequência.
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

}